"use client";
import {useState} from "react";

type Message={role:"user"|"assistant";content:string};

export default function HelpPage(){
 const [messages,setMessages]=useState<Message[]>([{role:"assistant",content:"Hey! I’m the Echo Productions technical assistant. Ask me about audio, AV, live production, video, lighting, streaming, networking, computers, software, hardware, or IT troubleshooting."}]);
 const [input,setInput]=useState(""); const [loading,setLoading]=useState(false);
 async function send(e:React.FormEvent){e.preventDefault();const q=input.trim();if(!q||loading)return;setInput("");setMessages(m=>[...m,{role:"user",content:q}]);setLoading(true);try{const r=await fetch("/api/help",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:q})});const d=await r.json();setMessages(m=>[...m,{role:"assistant",content:d.answer||d.error||"Something went wrong."}]);}finally{setLoading(false)}}
 return <main className="helpPage"><header className="pageHeader"><a href="/" className="brand">ECHO<span>PRODUCTIONS</span></a><span className="scopeBadge">PRODUCTION + IT</span></header><section className="helpHero"><p className="eyebrow">ECHO TECH ASSIST</p><h1>Ask how to make it work.</h1><p>Step-by-step help for live production and IT—from setting up a console to troubleshooting a network.</p></section><section className="chatBox"><div className="messages">{messages.map((m,i)=><div className={"message "+m.role} key={i}><span>{m.role==="assistant"?"ECHO":"YOU"}</span><p>{m.content}</p></div>)}{loading&&<div className="message assistant"><span>ECHO</span><p>Thinking…</p></div>}</div><form onSubmit={send}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask a production or IT question..." aria-label="Production or IT question"/><button className="primaryButton" disabled={loading}>Ask →</button></form></section><p className="scopeNote">Echo Tech is intentionally limited to production and IT topics.</p></main>}